//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banned
    {
        public int id_banned { get; set; }
        public int id_user { get; set; }
        public string ban_type { get; set; }
        public string reason { get; set; }
        public System.DateTime banned_at { get; set; }
        public Nullable<System.DateTime> unbanned_at { get; set; }
    
        public virtual User User { get; set; }
    }
}
