//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedia
    {
        public int id_social_media { get; set; }
        public int id_user { get; set; }
        public string facebook { get; set; }
        public string instagram { get; set; }
        public string tiktok { get; set; }
        public string twitter { get; set; }
    
        public virtual User User { get; set; }
    }
}
